server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #限制文件上传大小
#Eureka
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #每隔五秒发送一次心跳机制
    lease-expiration-duration-in-seconds: 10 #如果10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${sever.port}